# Generated by Django 3.0.2 on 2020-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/structure/', verbose_name='Фото')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('education', models.TextField(blank=True, null=True, verbose_name='Образование')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
        ),
    ]
