# Generated by Django 3.0.2 on 2020-02-11 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200211_2244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Structure',
            new_name='Employees',
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ('created',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
