# Generated by Django 3.0.2 on 2020-02-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200211_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=100, verbose_name='Должность')),
                ('content', models.TextField(verbose_name='Контент')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ('created',),
            },
        ),
    ]
