# Generated by Django 3.0.2 on 2020-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='about/documents/%Y-%m-%d/', verbose_name='Файл'),
        ),
    ]
