# Generated by Django 3.0.3 on 2020-02-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20200212_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Почта'),
        ),
    ]
