# Generated by Django 3.0.3 on 2020-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20200214_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='show_photo',
            field=models.BooleanField(default=1, verbose_name='Показывать фото'),
        ),
    ]
