# Generated by Django 3.0.3 on 2020-02-16 07:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_employees_show_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Announcing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
