# Generated by Django 3.0.3 on 2020-02-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20200216_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcing',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
    ]
