# Generated by Django 3.0.3 on 2020-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20200218_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcing',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
