# Generated by Django 3.0.3 on 2020-03-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_auto_20200218_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcing/%Y/%m/%d/', verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='announcing',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Первоисточник'),
        ),
        migrations.AlterField(
            model_name='announcing',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
