# Generated by Django 3.0.3 on 2020-03-30 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20200330_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcing',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
