# Generated by Django 3.0.3 on 2020-03-31 11:48

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_announcing_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/%Y/%m/%d/', verbose_name='Фото')),
                ('content', tinymce.models.HTMLField(verbose_name='Контент')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
                'ordering': ('created',),
            },
        ),
        migrations.AlterField(
            model_name='announcing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcing/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
