# Generated by Django 3.0.3 on 2020-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_contacts_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='ontop',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='visible',
        ),
        migrations.AlterField(
            model_name='contacts',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='Карта'),
        ),
    ]
