# Generated by Django 3.0.3 on 2020-04-07 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_auto_20200404_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcing',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='map',
            field=models.TextField(blank=True, help_text='Конструктор: https://yandex.ru/maps/?um=constructor%3A98308fdfb6d76ece12d73780c3ab9e45d1162b227971510aa97ba97a190135cc&source=constructorLink', null=True, verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='history',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
    ]
