# Generated by Django 3.0.3 on 2020-04-07 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20200407_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='documents',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='documents',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.FileField(upload_to='about/documents/%Y-%m-%d/', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название документа'),
        ),
    ]
