# Generated by Django 3.0.3 on 2020-04-07 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_auto_20200407_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='file',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='name',
        ),
        migrations.CreateModel(
            name='DocumentsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='about/documents/%Y-%m-%d/', verbose_name='Документ')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('documents', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_files', to='about.Documents', verbose_name='Связанные документы')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('created',),
            },
        ),
    ]
