# Generated by Django 3.0.3 on 2020-05-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0019_auto_20200407_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='ontop',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='ontop',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='ontop',
        ),
    ]
