# Generated by Django 3.0.3 on 2020-05-15 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0021_auto_20200515_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique_for_date='publish', verbose_name='ЧПУ'),
            preserve_default=False,
        ),
    ]
