# Generated by Django 3.0.3 on 2020-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0022_documents_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='visible',
            field=models.BooleanField(default=1, verbose_name='Показывать'),
        ),
    ]
