# Generated by Django 3.0.3 on 2020-05-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0023_contacts_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='ontop',
        ),
    ]
