# Generated by Django 3.0.3 on 2020-05-27 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import myapps.about.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0024_remove_employees_ontop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique_for_date='publish', verbose_name='ЧПУ')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='ProjectsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('file', models.FileField(upload_to=myapps.about.models.proj_dir_path, verbose_name='Документ')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('projects', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_files', to='about.Projects', verbose_name='Связанные проекты')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ('created',),
            },
        ),
    ]
