# Generated by Django 3.0.3 on 2020-05-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0025_projects_projectsfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ('created',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Структура'},
        ),
    ]
