# Generated by Django 3.0.3 on 2020-06-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0026_auto_20200527_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
    ]
