# Generated by Django 3.0.2 on 2020-02-04 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, verbose_name='ЧПУ')),
                ('keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ключевые слова')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsimages/', verbose_name='Главное фото')),
                ('imagesign', models.CharField(blank=True, max_length=100, null=True, verbose_name='Подпись к главному фото')),
                ('content', models.TextField(verbose_name='Контент')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Источник')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('ontop', models.BooleanField(default=0, verbose_name='Размещать сверху')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('publish', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-created',),
            },
        ),
    ]
