# Generated by Django 3.0.2 on 2020-02-08 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200204_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsimages',
            options={'ordering': ('-created',), 'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('publications', 'Публикация'), ('announcements', 'Объявление')], default='news', max_length=13),
        ),
        migrations.AlterField(
            model_name='news',
            name='ontop',
            field=models.BooleanField(verbose_name='Размещать сверху'),
        ),
        migrations.AlterField(
            model_name='news',
            name='visible',
            field=models.BooleanField(default=1, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='news.News', verbose_name='Связанная новость'),
        ),
    ]
