# Generated by Django 3.0.2 on 2020-02-08 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200208_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Графический'), ('textimage', 'Текстографический')], default='image', max_length=13, verbose_name='Тип баннера')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('link', models.SlugField(max_length=200, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bannersimages/', verbose_name='Фото баннера')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания публикации:')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('news', 'Новости'), ('publications', 'Публикация'), ('announcements', 'Объявление')], default='news', max_length=13, verbose_name='Тип'),
        ),
    ]
