# Generated by Django 3.0.2 on 2020-02-08 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200208_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ('-created',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AddField(
            model_name='banners',
            name='end_publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания публикации:'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
