# Generated by Django 3.0.2 on 2020-02-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200208_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='link',
            field=models.CharField(max_length=200, verbose_name='Ссылка'),
        ),
    ]
