# Generated by Django 3.0.2 on 2020-02-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200208_2002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ('created',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='newsimages',
            options={'ordering': ('created',), 'verbose_name': 'фотография', 'verbose_name_plural': 'фотографии'},
        ),
        migrations.AlterField(
            model_name='banners',
            name='type',
            field=models.CharField(choices=[('with_image', 'Графический'), ('with_text_image', 'Текстографический')], default='image', max_length=15, verbose_name='Тип баннера'),
        ),
    ]
