# Generated by Django 3.0.2 on 2020-02-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200211_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bannersimages/%Y-%m-%d/', verbose_name='Фото баннера'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsimages/%Y/%m/%d/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsimages/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
