# Generated by Django 3.0.2 on 2020-02-12 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20200212_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimages',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
