# Generated by Django 3.0.2 on 2020-02-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsimages_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimages',
            name='title',
        ),
    ]
