# Generated by Django 3.0.2 on 2020-02-12 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_remove_newsimages_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsimages/%Y/%m/%d/', verbose_name='Фото')),
                ('visible', models.BooleanField(default=1, verbose_name='Показывать')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('news', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='news.News', verbose_name='Связанная новость')),
            ],
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='news.PhotoGallery', verbose_name='Связанная новость'),
        ),
    ]
