# Generated by Django 3.0.2 on 2020-02-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20200212_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ('created',), 'verbose_name': 'Фотогалерея', 'verbose_name_plural': 'Фотогалереи'},
        ),
        migrations.RenameField(
            model_name='newsimages',
            old_name='news',
            new_name='photogallery',
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='newsimages/%Y/%m/%d/', verbose_name='Главное фото'),
        ),
    ]
