# Generated by Django 3.0.2 on 2020-02-12 20:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200212_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='photogallery',
            name='slug',
            field=models.SlugField(default='dfsdfe', max_length=200, unique_for_date='publish', verbose_name='ЧПУ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('actual', 'Актуально'), ('news', 'Новости'), ('publications', 'Публикация'), ('announcements', 'Объявление')], max_length=13, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='newsimages',
            name='photogallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='news.PhotoGallery', verbose_name='Связанная новость'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photogallery', to='news.News', verbose_name='Связанная новость'),
        ),
    ]
