# Generated by Django 3.0.3 on 2020-02-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200212_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photogallery',
            options={'ordering': ('-created',), 'verbose_name': 'Фотогалерея', 'verbose_name_plural': 'Фотогалереи'},
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('actuals', 'Актуально'), ('news', 'Новости'), ('publications', 'Публикация'), ('announcements', 'Объявление')], max_length=13, verbose_name='Тип'),
        ),
    ]
