# Generated by Django 3.0.3 on 2020-02-14 09:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200213_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
