# Generated by Django 3.0.3 on 2020-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20200214_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Первоисточник'),
        ),
    ]
