# Generated by Django 3.0.3 on 2020-03-31 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20200331_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='end_publish',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата окончания публикации:'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='type',
            field=models.CharField(choices=[('with_image', 'Графический'), ('with_text', 'Текстовый'), ('with_image_text', 'Текстографический')], default='image', max_length=15, verbose_name='Тип баннера'),
        ),
    ]
