# Generated by Django 3.0.3 on 2020-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200331_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='end_publish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания публикации:'),
        ),
    ]
