# Generated by Django 3.0.3 on 2020-04-01 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0022_auto_20200331_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='related_news', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(choices=[('actuals', 'Актуально'), ('news', 'Новости'), ('publications', 'Публикации')], max_length=13, verbose_name='Тип'),
        ),
    ]
