# Generated by Django 3.0.3 on 2020-04-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20200401_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Первоисточник'),
        ),
    ]
