# Generated by Django 3.0.3 on 2020-04-07 05:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_photogallery_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='photogallery',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата публикации'),
        ),
    ]
