# Generated by Django 3.0.3 on 2020-04-07 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200407_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banners',
            name='end_publish',
        ),
    ]
