# Generated by Django 3.0.3 on 2020-04-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_remove_banners_end_publish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsImages',
            new_name='PhotoGalleryImages',
        ),
    ]
