# Generated by Django 3.0.3 on 2020-04-08 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20200407_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photogalleryimages',
            name='photogallery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photogallery_images', to='news.PhotoGallery', verbose_name='Связанная новость'),
        ),
    ]
