# Generated by Django 3.0.3 on 2020-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_auto_20200408_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='imagesign',
            field=models.CharField(blank=True, help_text='Короткое описание к главному фото', max_length=70, null=True, verbose_name='Подпись к главному фото'),
        ),
    ]
