# Generated by Django 3.0.3 on 2020-04-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_videogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videogallery',
            name='youtube_video',
        ),
        migrations.AddField(
            model_name='videogallery',
            name='cap',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Видео cap.ru'),
        ),
        migrations.AddField(
            model_name='videogallery',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео YouTube'),
        ),
    ]
