# Generated by Django 3.0.3 on 2020-04-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_auto_20200408_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogallery',
            name='cap',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Видео CAP.RU'),
        ),
        migrations.AlterField(
            model_name='videogallery',
            name='youtube',
            field=models.CharField(blank=True, help_text='КОД ВИДЕО', max_length=100, null=True, verbose_name='Видео YouTube'),
        ),
    ]
