# Generated by Django 3.0.3 on 2020-04-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20200414_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='photogallery',
        ),
    ]
