# Generated by Django 3.0.3 on 2020-04-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_remove_news_photogallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='ontop',
        ),
    ]
