# Generated by Django 3.0.3 on 2020-05-12 08:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_remove_news_ontop'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
