# Generated by Django 3.0.3 on 2020-05-12 14:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0036_photogallery_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
