# Generated by Django 3.0.3 on 2020-05-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0038_auto_20200513_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='image',
            field=models.ImageField(blank=True, help_text='Превью изображение видео', null=True, upload_to='newsvideos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
