# Generated by Django 3.0.3 on 2020-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0039_videonews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='kod',
            field=models.TextField(blank=True, null=True, verbose_name='Код для вставки'),
        ),
    ]
