# Generated by Django 3.0.3 on 2020-05-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_news_kod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='kod',
        ),
    ]
