# Generated by Django 3.0.3 on 2020-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_remove_news_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='kod',
            field=models.TextField(blank=True, null=True, verbose_name='Код для вставки'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='youtube',
            field=models.CharField(blank=True, help_text='Код видео', max_length=100, null=True, verbose_name='Видео YouTube'),
        ),
    ]
