# Generated by Django 3.0.3 on 2020-05-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_auto_20200520_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='videonews',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео Instagram'),
        ),
    ]
