# Generated by Django 4.0.4 on 2022-05-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_videonews_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='on_telegram',
            field=models.BooleanField(default=0, verbose_name='Показывать'),
        ),
        migrations.AlterField(
            model_name='videonews',
            name='youtube',
            field=models.CharField(blank=True, help_text='Код видео. Например "XyfjVLIAYCU"', max_length=100, null=True, verbose_name='Видео YouTube'),
        ),
    ]
