# Generated by Django 4.0.4 on 2022-05-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0044_news_on_telegram_alter_videonews_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='on_telegram',
            field=models.BooleanField(default=0, verbose_name='Опубликовать в Телеграм'),
        ),
    ]
