# Generated by Django 4.0.4 on 2022-05-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0045_alter_news_on_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='on_telegram',
        ),
        migrations.AddField(
            model_name='news',
            name='on_socialnet',
            field=models.BooleanField(default=False, verbose_name='Опубликовать в соцсетях'),
        ),
    ]
